name: kconst
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: ^18.3.44
  cupertino_icons: ^1.0.0
  http: ^0.12.0+2
  shared_preferences: ^0.5.3+4
  image_picker: ^0.6.2+3
  progress_dialog: ^1.2.4
  curved_navigation_bar: ^0.3.2
  google_maps_flutter: ^1.0.6
  geolocator: ^6.1.4
  charts_flutter: ^0.9.0
  dio: ^3.0.6
  flutter_plugin_pdf_viewer: ^1.0.7
  intl: ^0.16.1
  fl_chart: ^0.12.0
  carousel_pro: ^1.0.0
  webview_flutter: ^0.3.3
  video_player: ^0.10.8+1
  flick_video_player: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/imagenotfound.png
    - assets/images/logout.png
    - assets/images/noimage.png
    - assets/images/story.png
    - assets/images/title.png
    - assets/images/message.png
    - assets/images/exit.png
    - assets/images/menu.png
    - assets/images/iconssatu.png
    - assets/images/arrowright.png
    - assets/images/logo_bpjt.png
    - assets/images/thumbnail.png
    - assets/images/thumbnail2.png
    - assets/iconk3/ic_covid.png
    - assets/iconk3/ic_fatalitas.png
    - assets/iconk3/ic_insiden.png
    - assets/iconk3/ic_jamkerja.png
    - assets/iconk3/ic_nearmis.png
    - assets/iconk3/ic_pekerja.png
    - assets/iconk3/ic_pelatihan.png
    - assets/iconk3/ic_profile.png
    - assets/iconk3/signin.png
    - assets/data.json
    - assets/carousel/carousel1.png
    - assets/carousel/carousel2.png
    - assets/carousel/carousatu.png
    - assets/carousel/caroudua.png
    - assets/carousel/caroutiga.png
    - assets/carousel/carouempat.png
    - assets/icon/icon_dashboard.png
    - assets/icon/konstruksi.png
    - assets/icon/persiapan.png
    - assets/icon/operasi.png
    - assets/icon/jabodetabek.jpg
    - assets/icon/nontransjawa.jpg
    - assets/icon/transjawa.jpg
    - assets/icon/transsumatera.jpg
    - assets/icon/logopu.jpg
    - assets/icon/drone.png
    - assets/icon/facebook.png
    - assets/icon/instagram.png
    - assets/icon/youtube.png
    - assets/icon/twitter.png
    - assets/icon/cone.png

  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
